version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-bibliotecaob
    environment:
      POSTGRES_DB: railway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: D-B*EcGA4*bA6*gA4ED*DC*c-2cDecfg 
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres.railway.internal:5432/railway
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: D-B*EcGA4*bA6*gA4ED*DC*c-2cDecfg 
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

