version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-bibliotecaob
    environment:
      POSTGRES_DB: bibliotecaob
      POSTGRES_USER: bibliotecaob
      POSTGRES_PASSWORD: iYQAPXtBJO6l932oXdKwqcxizHk5UjT8
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cmaqbta1hbls73cnbdg0-a.oregon-postgres.render.com/bibliotecaob
      SPRING_DATASOURCE_USERNAME: bibliotecaob
      SPRING_DATASOURCE_PASSWORD: iYQAPXtBJO6l932oXdKwqcxizHk5UjT8
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

